spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/postgre_local
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changeLog-master.groovy

server:
  servlet:
    context-path: "/api"
